import { Inter } from "next/font/google";
import "../styles/globals.css"; // Import your global styles

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="App">
          <nav className="bg-gray-800 p-4 text-white">
            <ul className="flex space-x-4">
              <li>
                <a href="/">Home</a> {/* Use <a> for simple navigation */}
              </li>
              <li>
                <a href="/management">Management</a>
              </li>
            </ul>
          </nav>
          <div className="container mx-auto mt-8">
            {children}
          </div>
          <footer className="text-center mt-8">&copy; Elgin Sharper - Crud app</footer>
        </div>
      </body>
    </html>
  );
}
